apiVersion: v2
name: dawarich
description: "Self-hosted alternative to Google Location History"
type: application
version: 0.6.3
# renovate datasource=docker depName=docker.io/freikin/dawarich
appVersion: "0.25.6"
dependencies:
  - name: postgresql
    version: 16.6.4
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 20.13.2
sources:
  - https://dawarich.app
